# Generated by Django 2.0.2 on 2018-05-03 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 13, 18, 46, 233932)),
        ),
    ]
