# Generated by Django 2.0.2 on 2018-03-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180309_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='times_viewed',
            field=models.IntegerField(default=0),
        ),
    ]
