# Generated by Django 2.0.2 on 2018-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CvEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('function', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_percentage', models.IntegerField(default=100)),
                ('mastered_percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cventry',
            name='projects',
            field=models.ManyToManyField(to='cv.Project'),
        ),
        migrations.AddField(
            model_name='cventry',
            name='resources',
            field=models.ManyToManyField(to='cv.Resource'),
        ),
        migrations.AddField(
            model_name='cventry',
            name='skills',
            field=models.ManyToManyField(to='cv.Skill'),
        ),
    ]
