# Generated by Django 2.0.2 on 2018-05-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(default='', height_field=200, upload_to='cv/documents/', width_field=200),
        ),
    ]
