# Generated by Django 2.0.2 on 2018-05-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cventry',
            name='image',
            field=models.ImageField(default='', upload_to='cv/headshots/'),
        ),
    ]
